"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "sparkles"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion, useAnimation } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimationHandlers } from "./useIconAnimation";

const SPARKLE_VARIANTS: Variants = {
  initial: {
    y: 0,
    fill: "none",
  },
  hover: {
    y: [0, -1, 0, 0],
    fill: "currentColor",
    transition: {
      duration: 1,
      bounce: 0.3,
    },
  },
};

const STAR_VARIANTS: Variants = {
  initial: {
    opacity: 1,
    x: 0,
    y: 0,
  },
  blink: () => ({
    opacity: [0, 1, 0, 0, 0, 0, 1],
    transition: {
      duration: 2,
      type: "spring",
      stiffness: 70,
      damping: 10,
      mass: 0.4,
    },
  }),
};

/** Props for {@link AIIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type AIIconProps = AnimatedIconProps;

/** Imperative handle for {@link AIIcon}, via its `controlRef` prop. */
export type AIIconHandle = AnimatedIconHandle;

/**
 * Animated AI icon — the animated twin of `AIIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { AIIcon } from "@fanvue/ui/animated-icons";
 *
 * <AIIcon size={24} />
 * ```
 */
export const AIIcon = React.forwardRef<SVGSVGElement, AIIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const starControls = useAnimation();
    const sparkleControls = useAnimation();

    const { handleMouseEnter, handleMouseLeave } = useIconAnimationHandlers({
      controls: [starControls, sparkleControls],
      controlRef,
      onMouseEnter,
      onMouseLeave,
      enter: ["hover", "blink"],
      leave: ["initial"],
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.path
          animate={sparkleControls}
          d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"
          variants={SPARKLE_VARIANTS}
        />
        <motion.path animate={starControls} d="M20 3v4" variants={STAR_VARIANTS} />
        <motion.path animate={starControls} d="M22 5h-4" variants={STAR_VARIANTS} />
        <motion.path animate={starControls} d="M4 17v2" variants={STAR_VARIANTS} />
        <motion.path animate={starControls} d="M5 18H3" variants={STAR_VARIANTS} />
      </svg>
    );
  },
);

AIIcon.displayName = "AIIcon";
