"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "arrow-down").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: { d: "m19 12-7 7-7-7", translateY: 0 },
  animate: {
    d: "m19 12-7 7-7-7",
    translateY: [0, -3, 0],
    transition: {
      duration: 0.4,
    },
  },
};

const SECOND_PATH_VARIANTS: Variants = {
  normal: { d: "M12 5v14" },
  animate: {
    d: ["M12 5v14", "M12 5v9", "M12 5v14"],
    transition: {
      duration: 0.4,
    },
  },
};

/** Props for {@link ArrowDownIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type ArrowDownIconProps = AnimatedIconProps;

/** Imperative handle for {@link ArrowDownIcon}, via its `controlRef` prop. */
export type ArrowDownIconHandle = AnimatedIconHandle;

/**
 * Animated ArrowDown icon — the animated twin of `ArrowDownIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { ArrowDownIcon } from "@fanvue/ui/animated-icons";
 *
 * <ArrowDownIcon size={24} />
 * ```
 */
export const ArrowDownIcon = React.forwardRef<SVGSVGElement, ArrowDownIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.path animate={controls} d="m19 12-7 7-7-7" variants={PATH_VARIANTS} />
        <motion.path animate={controls} d="M12 5v14" variants={SECOND_PATH_VARIANTS} />
      </svg>
    );
  },
);

ArrowDownIcon.displayName = "ArrowDownIcon";
