"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "arrow-left"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: { d: "m12 19-7-7 7-7", translateX: 0 },
  animate: {
    d: "m12 19-7-7 7-7",
    translateX: [0, 3, 0],
    transition: {
      duration: 0.4,
    },
  },
};

const SECOND_PATH_VARIANTS: Variants = {
  normal: { d: "M19 12H5" },
  animate: {
    d: ["M19 12H5", "M19 12H10", "M19 12H5"],
    transition: {
      duration: 0.4,
    },
  },
};

/** Props for {@link ArrowLeftIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type ArrowLeftIconProps = AnimatedIconProps;

/** Imperative handle for {@link ArrowLeftIcon}, via its `controlRef` prop. */
export type ArrowLeftIconHandle = AnimatedIconHandle;

/**
 * Animated ArrowLeft icon — the animated twin of `ArrowLeftIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { ArrowLeftIcon } from "@fanvue/ui/animated-icons";
 *
 * <ArrowLeftIcon size={24} />
 * ```
 */
export const ArrowLeftIcon = React.forwardRef<SVGSVGElement, ArrowLeftIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.path animate={controls} d="m12 19-7-7 7-7" variants={PATH_VARIANTS} />
        <motion.path animate={controls} d="M19 12H5" variants={SECOND_PATH_VARIANTS} />
      </svg>
    );
  },
);

ArrowLeftIcon.displayName = "ArrowLeftIcon";
