"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "arrow-up-right").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const ARROW_VARIANTS: Variants = {
  normal: {
    scale: 1,
    translateX: 0,
    translateY: 0,
  },
  animate: {
    scale: [1, 0.85, 1],
    translateX: [0, -4, 0],
    translateY: [0, 4, 0],
    originX: 1,
    originY: 0,
    transition: {
      duration: 0.5,
      ease: "easeInOut",
    },
  },
};

/** Props for {@link ArrowUpRightIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type ArrowUpRightIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link ArrowUpRightIcon}, via its `controlRef` prop. */
export type ArrowUpRightIconHandle = AnimatedIconHandle;

/**
 * Animated ArrowUpRight icon — the animated twin of `ArrowUpRightIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-5` box as the static icon.
 *
 * @example
 * ```tsx
 * import { ArrowUpRightIcon } from "@fanvue/ui/animated-icons";
 *
 * <ArrowUpRightIcon />
 * ```
 */
export const ArrowUpRightIcon = React.forwardRef<SVGSVGElement, ArrowUpRightIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-5", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.g animate={controls} variants={ARROW_VARIANTS}>
          <path d="M7 7H17" />
          <path d="M17 7V17" />
          <path d="M7 17L17 7" />
        </motion.g>
      </svg>
    );
  },
);

ArrowUpRightIcon.displayName = "ArrowUpRightIcon";
