"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "circle-check").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: {
    opacity: 1,
    pathLength: 1,
    transition: {
      duration: 0.3,
      opacity: { duration: 0.1 },
    },
  },
  animate: {
    opacity: [0, 1],
    pathLength: [0, 1],
    transition: {
      duration: 0.4,
      opacity: { duration: 0.1 },
    },
  },
};

/** Props for {@link CheckOutlineIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type CheckOutlineIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link CheckOutlineIcon}, via its `controlRef` prop. */
export type CheckOutlineIconHandle = AnimatedIconHandle;

/**
 * Animated CheckOutline icon — the animated twin of `CheckOutlineIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-5` box as the static icon.
 *
 * @example
 * ```tsx
 * import { CheckOutlineIcon } from "@fanvue/ui/animated-icons";
 *
 * <CheckOutlineIcon />
 * ```
 */
export const CheckOutlineIcon = React.forwardRef<SVGSVGElement, CheckOutlineIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-5", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <circle cx="12" cy="12" r="10" />
        <motion.path
          animate={controls}
          d="m9 12 2 2 4-4"
          initial="normal"
          variants={PATH_VARIANTS}
        />
      </svg>
    );
  },
);

CheckOutlineIcon.displayName = "CheckOutlineIcon";
