"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "check").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: {
    opacity: 1,
    pathLength: 1,
    scale: 1,
    transition: {
      duration: 0.3,
      opacity: { duration: 0.1 },
    },
  },
  animate: {
    opacity: [0, 1],
    pathLength: [0, 1],
    scale: [0.5, 1],
    transition: {
      duration: 0.4,
      opacity: { duration: 0.1 },
    },
  },
};

/** Props for {@link CheckIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type CheckIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link CheckIcon}, via its `controlRef` prop. */
export type CheckIconHandle = AnimatedIconHandle;

/**
 * Animated Check icon — the animated twin of `CheckIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-3` box as the static icon.
 *
 * @example
 * ```tsx
 * import { CheckIcon } from "@fanvue/ui/animated-icons";
 *
 * <CheckIcon />
 * ```
 */
export const CheckIcon = React.forwardRef<SVGSVGElement, CheckIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-3", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.path
          animate={controls}
          d="M4 12 9 17L20 6"
          initial="normal"
          variants={PATH_VARIANTS}
        />
      </svg>
    );
  },
);

CheckIcon.displayName = "CheckIcon";
