"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "cog").
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link CogIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type CogIconProps = AnimatedIconProps;

/** Imperative handle for {@link CogIcon}, via its `controlRef` prop. */
export type CogIconHandle = AnimatedIconHandle;

/**
 * Animated Cog icon — the animated twin of `CogIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { CogIcon } from "@fanvue/ui/animated-icons";
 *
 * <CogIcon size={24} />
 * ```
 */
export const CogIcon = React.forwardRef<SVGSVGElement, CogIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        animate={controls}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        transition={{ type: "spring", stiffness: 50, damping: 10 }}
        variants={{
          normal: {
            rotate: 0,
          },
          animate: {
            rotate: 180,
          },
        }}
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" />
        <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
        <path d="M12 2v2" />
        <path d="M12 22v-2" />
        <path d="m17 20.66-1-1.73" />
        <path d="M11 10.27 7 3.34" />
        <path d="m20.66 17-1.73-1" />
        <path d="m3.34 7 1.73 1" />
        <path d="M14 12h8" />
        <path d="M2 12h2" />
        <path d="m20.66 7-1.73 1" />
        <path d="m3.34 17 1.73-1" />
        <path d="m17 3.34-1 1.73" />
        <path d="m11 13.73-4 6.93" />
      </motion.svg>
    );
  },
);

CogIcon.displayName = "CogIcon";
