"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "x"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: {
    opacity: 1,
    pathLength: 1,
  },
  animate: {
    opacity: [0, 1],
    pathLength: [0, 1],
  },
};

/** Props for {@link CrossIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type CrossIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link CrossIcon}, via its `controlRef` prop. */
export type CrossIconHandle = AnimatedIconHandle;

/**
 * Animated Cross icon — the animated twin of `CrossIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Sized via `className`, defaulting to the same `size-5` box as the static icon.
 *
 * @example
 * ```tsx
 * import { CrossIcon } from "@fanvue/ui/animated-icons";
 *
 * <CrossIcon />
 * ```
 */
export const CrossIcon = React.forwardRef<SVGSVGElement, CrossIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn("size-5", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.path animate={controls} d="M18 6 6 18" variants={PATH_VARIANTS} />
        <motion.path
          animate={controls}
          d="m6 6 12 12"
          transition={{ delay: 0.2 }}
          variants={PATH_VARIANTS}
        />
      </svg>
    );
  },
);

CrossIcon.displayName = "CrossIcon";
