"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "discord"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const VARIANTS: Variants = {
  normal: {
    translateX: 0,
    opacity: 1,
    transition: {
      duration: 0.2,
    },
  },
  animate: {
    translateX: [0, -2, 2, -2, 2, 0],
    opacity: 1,
    transition: {
      duration: 0.4,
      times: [0, 0.2, 0.4, 0.6, 0.8, 1],
      ease: "easeInOut",
    },
  },
};

/** Props for {@link DiscordIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type DiscordIconProps = AnimatedIconProps;

/** Imperative handle for {@link DiscordIcon}, via its `controlRef` prop. */
export type DiscordIconHandle = AnimatedIconHandle;

/**
 * Animated Discord icon — the animated twin of `DiscordIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { DiscordIcon } from "@fanvue/ui/animated-icons";
 *
 * <DiscordIcon size={24} />
 * ```
 */
export const DiscordIcon = React.forwardRef<SVGSVGElement, DiscordIconProps>(
  (
    {
      size = 24,
      filled: _filled,
      className,
      style,
      controlRef,
      onMouseEnter,
      onMouseLeave,
      ...props
    },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 44 44"
        strokeWidth="3"
        className={cn(ICON_SIZE_CLASS[size], className)}
        style={{ overflow: "visible", ...style }}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.path
          animate={controls}
          d="M17.54,34.22A47.42,47.42,0,0,1,14.68,38C7.3,37.79,4.5,33,4.5,33A44.83,44.83,0,0,1,9.31,13.48,16.47,16.47,0,0,1,18.69,10l1,2.31"
          initial="normal"
          variants={VARIANTS}
        />
        <motion.path
          animate={controls}
          d="M17.85,22.67a3.48,3.48,0,0,0-3.37,3.9,3.38,3.38,0,0,0,3.31,3.22,3.53,3.53,0,0,0,3.43-3.9A3.45,3.45,0,0,0,17.85,22.67Z"
          initial="normal"
          variants={VARIANTS}
        />
        <motion.path
          animate={controls}
          d="M12.2,14.37a28.19,28.19,0,0,1,8.16-2.18A23.26,23.26,0,0,1,24,12a23.26,23.26,0,0,1,3.64.21,28.19,28.19,0,0,1,8.16,2.18m-7.47-2.09l1-2.31a16.47,16.47,0,0,1,9.38,3.51A44.83,44.83,0,0,1,43.5,33S40.7,37.79,33.32,38a47.42,47.42,0,0,1-2.86-3.81"
          initial="normal"
          variants={VARIANTS}
        />
        <motion.path
          animate={controls}
          d="M36.92,31.29a29.63,29.63,0,0,1-8.64,3.49,21.25,21.25,0,0,1-4.28.4h0a21.25,21.25,0,0,1-4.28-.4,29.63,29.63,0,0,1-8.64-3.49"
          initial="normal"
          variants={VARIANTS}
        />
        <motion.path
          animate={controls}
          d="M30.15,22.67a3.48,3.48,0,0,1,3.37,3.9,3.38,3.38,0,0,1-3.31,3.22,3.53,3.53,0,0,1-3.43-3.9A3.45,3.45,0,0,1,30.15,22.67Z"
          initial="normal"
          variants={VARIANTS}
        />
      </svg>
    );
  },
);

DiscordIcon.displayName = "DiscordIcon";
