"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "check-check"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { IconSize } from "../Icons/types";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: {
    opacity: 1,
    pathLength: 1,
    scale: 1,
    transition: {
      duration: 0.3,
      opacity: { duration: 0.1 },
    },
  },
  animate: (custom: number) => ({
    opacity: [0, 1],
    pathLength: [0, 1],
    scale: [0.5, 1],
    transition: {
      duration: 0.4,
      opacity: { duration: 0.1 },
      delay: 0.1 * custom,
    },
  }),
};

const STROKE_WIDTH: Record<IconSize, number> = {
  16: 2,
  24: 1.5,
  32: 1.5,
};

/** Props for {@link DoubleTickIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type DoubleTickIconProps = AnimatedIconProps;

/** Imperative handle for {@link DoubleTickIcon}, via its `controlRef` prop. */
export type DoubleTickIconHandle = AnimatedIconHandle;

/**
 * Animated DoubleTick icon — the animated twin of `DoubleTickIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { DoubleTickIcon } from "@fanvue/ui/animated-icons";
 *
 * <DoubleTickIcon size={24} />
 * ```
 */
export const DoubleTickIcon = React.forwardRef<SVGSVGElement, DoubleTickIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth={STROKE_WIDTH[size]}
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.path
          animate={controls}
          custom={0}
          d="M2 12 7 17L18 6"
          initial="normal"
          variants={PATH_VARIANTS}
        />
        <motion.path
          animate={controls}
          custom={1}
          d="M13 16L14.5 17.5L22 10"
          initial="normal"
          variants={PATH_VARIANTS}
        />
      </svg>
    );
  },
);

DoubleTickIcon.displayName = "DoubleTickIcon";
