"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "download").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const ARROW_VARIANTS: Variants = {
  normal: { y: 0 },
  animate: {
    y: 2,
    transition: {
      type: "spring",
      stiffness: 200,
      damping: 10,
      mass: 1,
    },
  },
};

/** Props for {@link DownloadIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type DownloadIconProps = AnimatedIconProps;

/** Imperative handle for {@link DownloadIcon}, via its `controlRef` prop. */
export type DownloadIconHandle = AnimatedIconHandle;

/**
 * Animated Download icon — the animated twin of `DownloadIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { DownloadIcon } from "@fanvue/ui/animated-icons";
 *
 * <DownloadIcon size={24} />
 * ```
 */
export const DownloadIcon = React.forwardRef<SVGSVGElement, DownloadIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
        <motion.g animate={controls} variants={ARROW_VARIANTS}>
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" x2="12" y1="15" y2="3" />
        </motion.g>
      </svg>
    );
  },
);

DownloadIcon.displayName = "DownloadIcon";
