"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "smile"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link EmojiIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type EmojiIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link EmojiIcon}, via its `controlRef` prop. */
export type EmojiIconHandle = AnimatedIconHandle;

/**
 * Animated Emoji icon — the animated twin of `EmojiIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Sized via `className`, defaulting to the same `size-6` box as the static icon.
 *
 * @example
 * ```tsx
 * import { EmojiIcon } from "@fanvue/ui/animated-icons";
 *
 * <EmojiIcon />
 * ```
 */
export const EmojiIcon = React.forwardRef<SVGSVGElement, EmojiIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    const faceVariants: Variants = {
      normal: {
        scale: 1,
        rotate: 0,
        strokeWidth: 1.5,
        transition: { duration: 0.3, ease: "easeOut" },
      },
      animate: {
        scale: [1, 1.15, 1.05, 1.1],
        rotate: [0, -3, 3, 0],
        strokeWidth: [1.5, 1.875, 1.875, 1.875],
        transition: {
          duration: 0.8,
          times: [0, 0.3, 0.6, 1],
          ease: "easeInOut",
        },
      },
    };

    const mouthVariants: Variants = {
      normal: {
        d: "M8 14s1.5 2 4 2 4-2 4-2",
        pathLength: 1,
        pathOffset: 0,
        strokeWidth: 1.5,
        transition: { duration: 0.3, ease: "easeOut" },
      },
      animate: {
        d: "M7 13.5s2.5 3.5 5 3.5 5-3.5 5-3.5",
        pathLength: [0.3, 1, 1],
        pathOffset: [0, 0, 0],
        strokeWidth: 1.875,
        transition: {
          d: { duration: 0.4, ease: "easeOut" },
          pathLength: {
            duration: 0.5,
            times: [0, 0.5, 1],
            ease: "easeInOut",
          },
          delay: 0.1,
        },
      },
    };

    const eyeVariants: Variants = {
      normal: {
        scale: 1,
        opacity: 1,
        transition: { duration: 0.3, ease: "easeOut" },
      },
      animate: {
        scale: [1, 1.5, 0.8, 1.2],
        opacity: [1, 1, 1, 1],
        transition: {
          duration: 0.5,
          times: [0, 0.3, 0.6, 1],
          ease: "easeInOut",
        },
      },
    };

    return (
      <motion.svg
        ref={ref}
        aria-hidden="true"
        {...props}
        animate={controls}
        fill="none"
        initial="normal"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        variants={faceVariants}
        viewBox="0 0 24 24"
        strokeWidth="1.5"
        className={cn("size-6", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.circle cx="12" cy="12" r="10" />
        <motion.path
          animate={controls}
          d="M8 14s1.5 2 4 2 4-2 4-2"
          initial="normal"
          variants={mouthVariants}
        />
        <motion.line
          animate={controls}
          initial="normal"
          variants={eyeVariants}
          x1="9"
          x2="9.01"
          y1="9"
          y2="9"
        />
        <motion.line
          animate={controls}
          initial="normal"
          variants={eyeVariants}
          x1="15"
          x2="15.01"
          y1="9"
          y2="9"
        />
      </motion.svg>
    );
  },
);

EmojiIcon.displayName = "EmojiIcon";
