"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "maximize-2").
import type { Transition } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const DEFAULT_TRANSITION: Transition = {
  type: "spring",
  stiffness: 250,
  damping: 25,
};

/** Props for {@link ExpandIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type ExpandIconProps = AnimatedIconProps;

/** Imperative handle for {@link ExpandIcon}, via its `controlRef` prop. */
export type ExpandIconHandle = AnimatedIconHandle;

/**
 * Animated Expand icon — the animated twin of `ExpandIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { ExpandIcon } from "@fanvue/ui/animated-icons";
 *
 * <ExpandIcon size={24} />
 * ```
 */
export const ExpandIcon = React.forwardRef<SVGSVGElement, ExpandIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.path
          animate={controls}
          d="M3 16.2V21m0 0h4.8M3 21l6-6"
          transition={DEFAULT_TRANSITION}
          variants={{
            normal: { translateX: "0%", translateY: "0%" },
            animate: { translateX: "-2px", translateY: "2px" },
          }}
        />
        <motion.path
          animate={controls}
          d="M21 7.8V3m0 0h-4.8M21 3l-6 6"
          transition={DEFAULT_TRANSITION}
          variants={{
            normal: { translateX: "0%", translateY: "0%" },
            animate: { translateX: "2px", translateY: "-2px" },
          }}
        />
      </svg>
    );
  },
);

ExpandIcon.displayName = "ExpandIcon";
