"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "flame"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: {
    pathLength: 1,
    opacity: 1,
    pathOffset: 0,
  },
  animate: {
    opacity: [0, 1],
    pathLength: [0, 1],
    transition: {
      delay: 0.1,
      duration: 0.4,
      opacity: { duration: 0.1, delay: 0.1 },
    },
  },
};

/** Props for {@link FlameIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type FlameIconProps = AnimatedIconProps;

/** Imperative handle for {@link FlameIcon}, via its `controlRef` prop. */
export type FlameIconHandle = AnimatedIconHandle;

/**
 * Animated Flame icon — the animated twin of `FlameIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { FlameIcon } from "@fanvue/ui/animated-icons";
 *
 * <FlameIcon size={24} />
 * ```
 */
export const FlameIcon = React.forwardRef<SVGSVGElement, FlameIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.path
          animate={controls}
          d="M8.9 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"
          fill="none"
          initial="normal"
          variants={PATH_VARIANTS}
        />
      </svg>
    );
  },
);

FlameIcon.displayName = "FlameIcon";
