"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "heart"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link HeartIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type HeartIconProps = AnimatedIconProps;

/** Imperative handle for {@link HeartIcon}, via its `controlRef` prop. */
export type HeartIconHandle = AnimatedIconHandle;

/**
 * Animated Heart icon — the animated twin of `HeartIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { HeartIcon } from "@fanvue/ui/animated-icons";
 *
 * <HeartIcon size={24} />
 * ```
 */
export const HeartIcon = React.forwardRef<SVGSVGElement, HeartIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        aria-hidden="true"
        {...props}
        animate={controls}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        variants={{
          normal: { scale: 1 },
          animate: {
            scale: [1, 1.08, 1],
            transition: {
              duration: 0.45,
              repeat: 2,
            },
          },
        }}
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
      </motion.svg>
    );
  },
);

HeartIcon.displayName = "HeartIcon";
