"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "circle-help").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const VARIANTS: Variants = {
  normal: { rotate: 0 },
  animate: { rotate: [0, -10, 10, -10, 0] },
};

/** Props for {@link HelpIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type HelpIconProps = AnimatedIconProps;

/** Imperative handle for {@link HelpIcon}, via its `controlRef` prop. */
export type HelpIconHandle = AnimatedIconHandle;

/**
 * Animated Help icon — the animated twin of `HelpIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { HelpIcon } from "@fanvue/ui/animated-icons";
 *
 * <HelpIcon size={24} />
 * ```
 */
export const HelpIcon = React.forwardRef<SVGSVGElement, HelpIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <circle cx="12" cy="12" r="10" />
        <motion.g
          animate={controls}
          transition={{
            duration: 0.5,
            ease: "easeInOut",
          }}
          variants={VARIANTS}
        >
          <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
          <path d="M12 17h.01" />
        </motion.g>
      </svg>
    );
  },
);

HelpIcon.displayName = "HelpIcon";
