"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "hourglass"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link HourglassIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type HourglassIconProps = AnimatedIconProps;

/** Imperative handle for {@link HourglassIcon}, via its `controlRef` prop. */
export type HourglassIconHandle = AnimatedIconHandle;

/**
 * Animated Hourglass icon — the animated twin of `HourglassIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { HourglassIcon } from "@fanvue/ui/animated-icons";
 *
 * <HourglassIcon size={24} />
 * ```
 */
export const HourglassIcon = React.forwardRef<SVGSVGElement, HourglassIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <motion.g
          animate={controls}
          style={{
            transformOrigin: "12px 12px",
          }}
          transition={{
            type: "spring",
            stiffness: 100,
            damping: 15,
            mass: 1,
          }}
          variants={{
            normal: {
              rotate: 0,
            },
            animate: {
              rotate: 180,
            },
          }}
        >
          <path d="M5 22h14" />
          <path d="M5 2h14" />
          <path d="M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22" />
          <path d="M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2" />
        </motion.g>
      </svg>
    );
  },
);

HourglassIcon.displayName = "HourglassIcon";
