"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "languages").
import type { Variants } from "motion/react";
import { motion, useAnimation } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, pathOffset: 0 },
  animate: (custom: number) => ({
    opacity: [0, 1],
    pathLength: [0, 1],
    pathOffset: [1, 0],
    transition: {
      opacity: { duration: 0.01, delay: custom * 0.1 },
      pathLength: {
        type: "spring",
        duration: 0.5,
        bounce: 0,
        delay: custom * 0.1,
      },
    },
  }),
};

const SVG_VARIANTS: Variants = {
  normal: { opacity: 1 },
  animate: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2,
    },
  },
};

/** Props for {@link LanguageIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type LanguageIconProps = AnimatedIconProps;

/** Imperative handle for {@link LanguageIcon}, via its `controlRef` prop. */
export type LanguageIconHandle = AnimatedIconHandle;

/**
 * Animated Language icon — the animated twin of `LanguageIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { LanguageIcon } from "@fanvue/ui/animated-icons";
 *
 * <LanguageIcon size={24} />
 * ```
 */
export const LanguageIcon = React.forwardRef<SVGSVGElement, LanguageIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const svgControls = useAnimation();
    const pathControls = useAnimation();

    const isControlledRef = React.useRef(false);

    React.useImperativeHandle(controlRef, () => {
      isControlledRef.current = true;

      return {
        startAnimation: () => {
          svgControls.start("animate");
          pathControls.start("animate");
        },
        stopAnimation: () => {
          svgControls.start("normal");
          pathControls.start("normal");
        },
      };
    });

    const handleMouseEnter = React.useCallback(
      (e: React.MouseEvent<SVGSVGElement>) => {
        if (isControlledRef.current) {
          onMouseEnter?.(e);
        } else {
          svgControls.start("animate");
          pathControls.start("animate");
        }
      },
      [onMouseEnter, pathControls, svgControls],
    );

    const handleMouseLeave = React.useCallback(
      (e: React.MouseEvent<SVGSVGElement>) => {
        if (isControlledRef.current) {
          onMouseLeave?.(e);
        } else {
          svgControls.start("normal");
          pathControls.start("normal");
        }
      },
      [svgControls, pathControls, onMouseLeave],
    );

    return (
      <motion.svg
        ref={ref}
        animate={svgControls}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        variants={SVG_VARIANTS}
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.path animate={pathControls} custom={3} d="m5 8 6 6" variants={PATH_VARIANTS} />
        <motion.path animate={pathControls} custom={2} d="m4 14 6-6 3-3" variants={PATH_VARIANTS} />
        <motion.path animate={pathControls} custom={1} d="M2 5h12" variants={PATH_VARIANTS} />
        <motion.path animate={pathControls} custom={0} d="M7 2h1" variants={PATH_VARIANTS} />
        <motion.path
          animate={pathControls}
          custom={3}
          d="m22 22-5-10-5 10"
          variants={PATH_VARIANTS}
        />
        <motion.path animate={pathControls} custom={3} d="M14 18h6" variants={PATH_VARIANTS} />
      </motion.svg>
    );
  },
);

LanguageIcon.displayName = "LanguageIcon";
