"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "lock-keyhole").
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link LockerIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type LockerIconProps = AnimatedIconProps;

/** Imperative handle for {@link LockerIcon}, via its `controlRef` prop. */
export type LockerIconHandle = AnimatedIconHandle;

/**
 * Animated Locker icon — the animated twin of `LockerIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { LockerIcon } from "@fanvue/ui/animated-icons";
 *
 * <LockerIcon size={24} />
 * ```
 */
export const LockerIcon = React.forwardRef<SVGSVGElement, LockerIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        animate={controls}
        fill="none"
        initial="normal"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        transition={{
          duration: 1,
          ease: [0.4, 0, 0.2, 1],
        }}
        variants={{
          normal: {
            rotate: 0,
            scale: 1,
          },
          animate: {
            rotate: [-3, 1, -2, 0],
            scale: [0.95, 1.05, 0.98, 1],
          },
        }}
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <circle cx="12" cy="16" r="1" />
        <rect height="12" rx="2" width="18" x="3" y="10" />
        <motion.path
          animate={controls}
          d="M7 10V7a5 5 0 0 1 10 0v3"
          initial="normal"
          transition={{
            duration: 0.3,
            ease: [0.4, 0, 0.2, 1],
          }}
          variants={{
            normal: {
              pathLength: 1,
            },
            animate: {
              pathLength: 0.7,
            },
          }}
        />
      </motion.svg>
    );
  },
);

LockerIcon.displayName = "LockerIcon";
