"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "panel-left-open"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Transition, Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const DEFAULT_TRANSITION: Transition = {
  times: [0, 0.4, 1],
  duration: 0.5,
};

const PATH_VARIANTS: Variants = {
  normal: { x: 0 },
  animate: { x: [0, 1.5, 0] },
};

/** Props for {@link MenuOpenIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type MenuOpenIconProps = AnimatedIconProps;

/** Imperative handle for {@link MenuOpenIcon}, via its `controlRef` prop. */
export type MenuOpenIconHandle = AnimatedIconHandle;

/**
 * Animated MenuOpen icon — the animated twin of `MenuOpenIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { MenuOpenIcon } from "@fanvue/ui/animated-icons";
 *
 * <MenuOpenIcon size={24} />
 * ```
 */
export const MenuOpenIcon = React.forwardRef<SVGSVGElement, MenuOpenIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <rect height="18" rx="2" width="18" x="3" y="3" />
        <path d="M9 3v18" />
        <motion.path
          animate={controls}
          d="m14 9 3 3-3 3"
          transition={DEFAULT_TRANSITION}
          variants={PATH_VARIANTS}
        />
      </svg>
    );
  },
);

MenuOpenIcon.displayName = "MenuOpenIcon";
