"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "menu").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const LINE_VARIANTS: Variants = {
  normal: {
    rotate: 0,
    y: 0,
    opacity: 1,
  },
  animate: (custom: number) => ({
    rotate: custom === 1 ? 45 : custom === 3 ? -45 : 0,
    y: custom === 1 ? 6 : custom === 3 ? -6 : 0,
    opacity: custom === 2 ? 0 : 1,
    transition: {
      type: "spring",
      stiffness: 260,
      damping: 20,
    },
  }),
};

/** Props for {@link MenuIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type MenuIconProps = AnimatedIconProps;

/** Imperative handle for {@link MenuIcon}, via its `controlRef` prop. */
export type MenuIconHandle = AnimatedIconHandle;

/**
 * Animated Menu icon — the animated twin of `MenuIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { MenuIcon } from "@fanvue/ui/animated-icons";
 *
 * <MenuIcon size={24} />
 * ```
 */
export const MenuIcon = React.forwardRef<SVGSVGElement, MenuIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.line
          animate={controls}
          custom={1}
          initial="normal"
          variants={LINE_VARIANTS}
          x1="4"
          x2="20"
          y1="6"
          y2="6"
        />
        <motion.line
          animate={controls}
          custom={2}
          initial="normal"
          variants={LINE_VARIANTS}
          x1="4"
          x2="20"
          y1="12"
          y2="12"
        />
        <motion.line
          animate={controls}
          custom={3}
          initial="normal"
          variants={LINE_VARIANTS}
          x1="4"
          x2="20"
          y1="18"
          y2="18"
        />
      </svg>
    );
  },
);

MenuIcon.displayName = "MenuIcon";
