"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "mic"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const CAPSULE_VARIANTS: Variants = {
  normal: { y: 0 },
  animate: {
    y: [0, -3, 0, -2, 0],
    transition: {
      duration: 0.6,
      ease: "easeInOut",
    },
  },
};

/** Props for {@link MicrophoneIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type MicrophoneIconProps = AnimatedIconProps;

/** Imperative handle for {@link MicrophoneIcon}, via its `controlRef` prop. */
export type MicrophoneIconHandle = AnimatedIconHandle;

/**
 * Animated Microphone icon — the animated twin of `MicrophoneIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { MicrophoneIcon } from "@fanvue/ui/animated-icons";
 *
 * <MicrophoneIcon size={24} />
 * ```
 */
export const MicrophoneIcon = React.forwardRef<SVGSVGElement, MicrophoneIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        overflow="visible"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <path d="M12 19v3" />
        <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
        <motion.rect
          animate={controls}
          height="13"
          rx="3"
          variants={CAPSULE_VARIANTS}
          width="6"
          x="9"
          y="2"
        />
      </svg>
    );
  },
);

MicrophoneIcon.displayName = "MicrophoneIcon";
