"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "plus").
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link PlusIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type PlusIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link PlusIcon}, via its `controlRef` prop. */
export type PlusIconHandle = AnimatedIconHandle;

/**
 * Animated Plus icon — the animated twin of `PlusIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-5` box as the static icon.
 *
 * @example
 * ```tsx
 * import { PlusIcon } from "@fanvue/ui/animated-icons";
 *
 * <PlusIcon />
 * ```
 */
export const PlusIcon = React.forwardRef<SVGSVGElement, PlusIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        animate={controls}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        transition={{ type: "spring", stiffness: 100, damping: 15 }}
        variants={{
          normal: {
            rotate: 0,
          },
          animate: {
            rotate: 180,
          },
        }}
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-5", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <path d="M5 12h14" />
        <path d="M12 5v14" />
      </motion.svg>
    );
  },
);

PlusIcon.displayName = "PlusIcon";
