"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "history").
import type { Transition, Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const ARROW_TRANSITION: Transition = {
  type: "spring",
  stiffness: 250,
  damping: 25,
};

const ARROW_VARIANTS: Variants = {
  normal: {
    rotate: "0deg",
  },
  animate: {
    rotate: "-50deg",
  },
};

const HAND_TRANSITION: Transition = {
  duration: 0.6,
  ease: [0.4, 0, 0.2, 1],
};

const HAND_VARIANTS: Variants = {
  normal: {
    rotate: 0,
    originX: "0%",
    originY: "100%",
  },
  animate: {
    rotate: -360,
    originX: "0%",
    originY: "100%",
  },
};

const MINUTE_HAND_TRANSITION: Transition = {
  duration: 0.5,
  ease: "easeInOut",
};

const MINUTE_HAND_VARIANTS: Variants = {
  normal: {
    rotate: 0,
    originX: "0%",
    originY: "0%",
  },
  animate: {
    rotate: -45,
    originX: "0%",
    originY: "0%",
  },
};

/** Props for {@link ReverseIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type ReverseIconProps = AnimatedIconProps;

/** Imperative handle for {@link ReverseIcon}, via its `controlRef` prop. */
export type ReverseIconHandle = AnimatedIconHandle;

/**
 * Animated Reverse icon — the animated twin of `ReverseIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { ReverseIcon } from "@fanvue/ui/animated-icons";
 *
 * <ReverseIcon size={24} />
 * ```
 */
export const ReverseIcon = React.forwardRef<SVGSVGElement, ReverseIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.g animate={controls} transition={ARROW_TRANSITION} variants={ARROW_VARIANTS}>
          <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
          <path d="M3 3v5h5" />
        </motion.g>
        <motion.line
          animate={controls}
          initial="normal"
          transition={HAND_TRANSITION}
          variants={HAND_VARIANTS}
          x1="12"
          x2="12"
          y1="12"
          y2="7"
        />
        <motion.line
          animate={controls}
          initial="normal"
          transition={MINUTE_HAND_TRANSITION}
          variants={MINUTE_HAND_VARIANTS}
          x1="12"
          x2="16"
          y1="12"
          y2="14"
        />
      </svg>
    );
  },
);

ReverseIcon.displayName = "ReverseIcon";
