"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "search"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link SearchIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type SearchIconProps = AnimatedIconProps;

/** Imperative handle for {@link SearchIcon}, via its `controlRef` prop. */
export type SearchIconHandle = AnimatedIconHandle;

/**
 * Animated Search icon — the animated twin of `SearchIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { SearchIcon } from "@fanvue/ui/animated-icons";
 *
 * <SearchIcon size={24} />
 * ```
 */
export const SearchIcon = React.forwardRef<SVGSVGElement, SearchIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        aria-hidden="true"
        {...props}
        animate={controls}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        transition={{
          duration: 1,
          bounce: 0.3,
        }}
        variants={{
          normal: { x: "0%", y: "0%" },
          animate: {
            x: ["0%", "0%", "-12.5%", "0%"],
            y: ["0%", "-16.6667%", "0%", "0%"],
          },
        }}
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <circle cx="11" cy="11" r="8" />
        <path d="m21 21-4.3-4.3" />
      </motion.svg>
    );
  },
);

SearchIcon.displayName = "SearchIcon";
