"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "send").
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link SendIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type SendIconProps = AnimatedIconProps;

/** Imperative handle for {@link SendIcon}, via its `controlRef` prop. */
export type SendIconHandle = AnimatedIconHandle;

/**
 * Animated Send icon — the animated twin of `SendIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { SendIcon } from "@fanvue/ui/animated-icons";
 *
 * <SendIcon size={24} />
 * ```
 */
export const SendIcon = React.forwardRef<SVGSVGElement, SendIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.g
          animate={controls}
          transition={{ duration: 0.5 }}
          variants={{
            normal: { x: 0, y: 0, scale: 1 },
            animate: {
              x: 3,
              y: -3,
              scale: 0.8,
            },
          }}
        >
          <path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z" />
          <path d="m21.854 2.147-10.94 10.939" />
        </motion.g>
        <motion.path
          animate={controls}
          d="M -3 28 C -0.5 26.8 1.6 24.6 3.3 22 C 4.8 19.7 5.2 17.6 4.2 16.1 C 3.2 14.7 1.4 14.5 0.3 15.8 C -0.9 17.2 -0.6 19.4 1.2 20.4 C 3.4 21.5 6.4 19.4 9 15.8"
          fill="none"
          initial={{ opacity: 0, pathLength: 0 }}
          stroke="currentColor"
          strokeDasharray="2 2"
          strokeWidth="1"
          transition={{ duration: 0.55, delay: 0.1 }}
          variants={{
            normal: {
              pathLength: 0,
              opacity: 0,
              translateX: -3,
              translateY: 3,
              transition: { duration: 0.3 },
            },
            animate: {
              pathLength: 1,
              opacity: 1,
              translateX: 0,
              translateY: 0,
            },
          }}
        />
      </svg>
    );
  },
);

SendIcon.displayName = "SendIcon";
