"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "sun"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1 },
  animate: (i: number) => ({
    opacity: [0, 1],
    transition: { delay: i * 0.1, duration: 0.3 },
  }),
};

/** Props for {@link SunIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type SunIconProps = AnimatedIconProps;

/** Imperative handle for {@link SunIcon}, via its `controlRef` prop. */
export type SunIconHandle = AnimatedIconHandle;

/**
 * Animated Sun icon — the animated twin of `SunIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { SunIcon } from "@fanvue/ui/animated-icons";
 *
 * <SunIcon size={24} />
 * ```
 */
export const SunIcon = React.forwardRef<SVGSVGElement, SunIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <circle cx="12" cy="12" r="4" />
        {[
          "M12 2v2",
          "m19.07 4.93-1.41 1.41",
          "M20 12h2",
          "m17.66 17.66 1.41 1.41",
          "M12 20v2",
          "m6.34 17.66-1.41 1.41",
          "M2 12h2",
          "m4.93 4.93 1.41 1.41",
        ].map((d, index) => (
          <motion.path
            animate={controls}
            custom={index + 1}
            d={d}
            key={d}
            variants={PATH_VARIANTS}
          />
        ))}
      </svg>
    );
  },
);

SunIcon.displayName = "SunIcon";
