"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "upvote"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link ThumbUpIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type ThumbUpIconProps = AnimatedIconProps;

/** Imperative handle for {@link ThumbUpIcon}, via its `controlRef` prop. */
export type ThumbUpIconHandle = AnimatedIconHandle;

/**
 * Animated ThumbUp icon — the animated twin of `ThumbUpIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { ThumbUpIcon } from "@fanvue/ui/animated-icons";
 *
 * <ThumbUpIcon size={24} />
 * ```
 */
export const ThumbUpIcon = React.forwardRef<SVGSVGElement, ThumbUpIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        aria-hidden="true"
        {...props}
        animate={controls}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        transition={{ type: "spring", stiffness: 250, damping: 25 }}
        variants={{
          normal: {
            translateX: "0%",
            translateY: "0%",
            rotate: "0deg",
          },
          animate: {
            translateX: "-4.1667%",
            translateY: "-8.3333%",
            rotate: "-12deg",
          },
        }}
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <path d="M7 10v12" />
        <path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z" />
      </motion.svg>
    );
  },
);

ThumbUpIcon.displayName = "ThumbUpIcon";
