"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "downvote"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

/** Props for {@link ThumbDownIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type ThumbDownIconProps = AnimatedIconProps;

/** Imperative handle for {@link ThumbDownIcon}, via its `controlRef` prop. */
export type ThumbDownIconHandle = AnimatedIconHandle;

/**
 * Animated ThumbDown icon — the animated twin of `ThumbDownIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { ThumbDownIcon } from "@fanvue/ui/animated-icons";
 *
 * <ThumbDownIcon size={24} />
 * ```
 */
export const ThumbDownIcon = React.forwardRef<SVGSVGElement, ThumbDownIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        aria-hidden="true"
        {...props}
        animate={controls}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        transition={{ type: "spring", stiffness: 250, damping: 25 }}
        variants={{
          normal: {
            translateX: "0%",
            translateY: "0%",
            rotate: "0deg",
          },
          animate: {
            translateX: "-4.1667%",
            translateY: "8.3333%",
            rotate: "-12deg",
          },
        }}
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <path d="M17 14V2" />
        <path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z" />
      </motion.svg>
    );
  },
);

ThumbDownIcon.displayName = "ThumbDownIcon";
