"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "circle-check").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const PATH_VARIANTS: Variants = {
  normal: {
    opacity: 1,
    pathLength: 1,
    transition: {
      duration: 0.3,
      opacity: { duration: 0.1 },
    },
  },
  animate: {
    opacity: [0, 1],
    pathLength: [0, 1],
    transition: {
      duration: 0.4,
      opacity: { duration: 0.1 },
    },
  },
};

/** Props for {@link TickCircleIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type TickCircleIconProps = AnimatedIconProps;

/** Imperative handle for {@link TickCircleIcon}, via its `controlRef` prop. */
export type TickCircleIconHandle = AnimatedIconHandle;

/**
 * Animated TickCircle icon — the animated twin of `TickCircleIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Renders at sizes 16, 24, or 32 px — the same box as the static icon.
 *
 * @example
 * ```tsx
 * import { TickCircleIcon } from "@fanvue/ui/animated-icons";
 *
 * <TickCircleIcon size={24} />
 * ```
 */
export const TickCircleIcon = React.forwardRef<SVGSVGElement, TickCircleIconProps>(
  ({ size = 24, className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <circle cx="12" cy="12" r="10" />
        <motion.path
          animate={controls}
          d="m9 12 2 2 4-4"
          initial="normal"
          variants={PATH_VARIANTS}
        />
      </svg>
    );
  },
);

TickCircleIcon.displayName = "TickCircleIcon";
