"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "delete").
import type { Transition, Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const LID_VARIANTS: Variants = {
  normal: { y: 0 },
  animate: { y: -1.1 },
};

const SPRING_TRANSITION: Transition = {
  type: "spring",
  stiffness: 500,
  damping: 30,
};

/** Props for {@link TrashBinIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type TrashBinIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link TrashBinIcon}, via its `controlRef` prop. */
export type TrashBinIconHandle = AnimatedIconHandle;

/**
 * Animated TrashBin icon — the animated twin of `TrashBinIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-6` box as the static icon.
 *
 * @example
 * ```tsx
 * import { TrashBinIcon } from "@fanvue/ui/animated-icons";
 *
 * <TrashBinIcon />
 * ```
 */
export const TrashBinIcon = React.forwardRef<SVGSVGElement, TrashBinIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-6", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <motion.g animate={controls} transition={SPRING_TRANSITION} variants={LID_VARIANTS}>
          <path d="M3 6h18" />
          <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
        </motion.g>
        <motion.path
          animate={controls}
          d="M19 8v12c0 1-1 2-2 2H7c-1 0-2-1-2-2V8"
          transition={SPRING_TRANSITION}
          variants={{
            normal: { d: "M19 8v12c0 1-1 2-2 2H7c-1 0-2-1-2-2V8" },
            animate: { d: "M19 9v12c0 1-1 2-2 2H7c-1 0-2-1-2-2V9" },
          }}
        />
        <motion.line
          animate={controls}
          transition={SPRING_TRANSITION}
          variants={{
            normal: { y1: 11, y2: 17 },
            animate: { y1: 11.5, y2: 17.5 },
          }}
          x1="10"
          x2="10"
          y1="11"
          y2="17"
        />
        <motion.line
          animate={controls}
          transition={SPRING_TRANSITION}
          variants={{
            normal: { y1: 11, y2: 17 },
            animate: { y1: 11.5, y2: 17.5 },
          }}
          x1="14"
          x2="14"
          y1="11"
          y2="17"
        />
      </svg>
    );
  },
);

TrashBinIcon.displayName = "TrashBinIcon";
