"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "cloud-upload"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { IconSize } from "../Icons/types";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const CLOUD_VARIANTS: Variants = {
  initial: { y: -2 },
  active: { y: 0 },
};

const STROKE_WIDTH: Record<IconSize, number> = {
  16: 2,
  24: 1.5,
  32: 1.5,
};

/** Props for {@link UploadToCloudIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type UploadToCloudIconProps = AnimatedIconProps;

/** Imperative handle for {@link UploadToCloudIcon}, via its `controlRef` prop. */
export type UploadToCloudIconHandle = AnimatedIconHandle;

/**
 * Animated UploadToCloud icon — the animated twin of `UploadToCloudIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { UploadToCloudIcon } from "@fanvue/ui/animated-icons";
 *
 * <UploadToCloudIcon size={24} />
 * ```
 */
export const UploadToCloudIcon = React.forwardRef<SVGSVGElement, UploadToCloudIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
      enter: ["initial"],
      leave: ["active"],
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth={STROKE_WIDTH[size]}
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <path d="M4.2 15.1A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.2" />
        <motion.g
          animate={controls}
          transition={{
            duration: 0.3,
            ease: [0.68, -0.6, 0.32, 1.6],
          }}
          variants={CLOUD_VARIANTS}
        >
          <path d="M12 13v8" />
          <path d="m8 17 4-4 4 4" />
        </motion.g>
      </svg>
    );
  },
);

UploadToCloudIcon.displayName = "UploadToCloudIcon";
