"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "cloud-upload").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const CLOUD_VARIANTS: Variants = {
  initial: { y: -2 },
  active: { y: 0 },
};

/** Props for {@link UploadCloudIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type UploadCloudIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link UploadCloudIcon}, via its `controlRef` prop. */
export type UploadCloudIconHandle = AnimatedIconHandle;

/**
 * Animated UploadCloud icon — the animated twin of `UploadCloudIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-5` box as the static icon.
 *
 * @example
 * ```tsx
 * import { UploadCloudIcon } from "@fanvue/ui/animated-icons";
 *
 * <UploadCloudIcon />
 * ```
 */
export const UploadCloudIcon = React.forwardRef<SVGSVGElement, UploadCloudIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-5", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <path d="M4.2 15.1A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.2" />
        <motion.g
          animate={controls}
          transition={{
            duration: 0.3,
            ease: [0.68, -0.6, 0.32, 1.6],
          }}
          variants={CLOUD_VARIANTS}
        >
          <path d="M12 13v8" />
          <path d="m8 17 4-4 4 4" />
        </motion.g>
      </svg>
    );
  },
);

UploadCloudIcon.displayName = "UploadCloudIcon";
