"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "wifi").
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const WIFI_LEVELS = [
  { d: "M12 20h.01", initialOpacity: 1, delay: 0 },
  { d: "M8.5 16.429a5 5 0 0 1 7 0", initialOpacity: 1, delay: 0.1 },
  { d: "M5 12.859a10 10 0 0 1 14 0", initialOpacity: 1, delay: 0.2 },
  { d: "M2 8.82a15 15 0 0 1 20 0", initialOpacity: 1, delay: 0.3 },
];

/** Props for {@link WifiOnIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type WifiOnIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link WifiOnIcon}, via its `controlRef` prop. */
export type WifiOnIconHandle = AnimatedIconHandle;

/**
 * Animated WifiOn icon — the animated twin of `WifiOnIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-6` box as the static icon.
 *
 * @example
 * ```tsx
 * import { WifiOnIcon } from "@fanvue/ui/animated-icons";
 *
 * <WifiOnIcon />
 * ```
 */
export const WifiOnIcon = React.forwardRef<SVGSVGElement, WifiOnIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <svg
        ref={ref}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-6", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        {WIFI_LEVELS.map((level, index) => (
          <motion.path
            animate={controls}
            d={level.d}
            initial={{ opacity: level.initialOpacity }}
            key={index}
            variants={{
              fadeOut: {
                opacity: index === 0 ? 1 : 0,
                transition: { duration: 0.2 },
              },
              fadeIn: {
                opacity: 1,
                transition: {
                  type: "spring",
                  stiffness: 300,
                  damping: 20,
                  delay: level.delay,
                },
              },
            }}
          />
        ))}
      </svg>
    );
  },
);

WifiOnIcon.displayName = "WifiOnIcon";
