"use client";

/*! Animated icon artwork from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "wifi"). @license MIT */
// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import { ICON_SIZE_CLASS } from "../Icons/iconSizeClass";
import type { AnimatedIconHandle, AnimatedIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const WIFI_LEVELS = [
  { d: "M12 20h.01", initialOpacity: 1, delay: 0 },
  { d: "M8.5 16.429a5 5 0 0 1 7 0", initialOpacity: 1, delay: 0.1 },
  { d: "M5 12.859a10 10 0 0 1 14 0", initialOpacity: 1, delay: 0.2 },
  { d: "M2 8.82a15 15 0 0 1 20 0", initialOpacity: 1, delay: 0.3 },
];

/** Props for {@link WifiIcon}. See {@link AnimatedIconProps} for the shared shape. */
export type WifiIconProps = AnimatedIconProps;

/** Imperative handle for {@link WifiIcon}, via its `controlRef` prop. */
export type WifiIconHandle = AnimatedIconHandle;

/**
 * Animated Wifi icon — the animated twin of `WifiIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`, and stays
 * still when the user has asked for reduced motion.
 * Renders at sizes 16, 24, or 32 px — the same box and stroke weight as the static icon.
 *
 * @example
 * ```tsx
 * import { WifiIcon } from "@fanvue/ui/animated-icons";
 *
 * <WifiIcon size={24} />
 * ```
 */
export const WifiIcon = React.forwardRef<SVGSVGElement, WifiIconProps>(
  (
    { size = 24, filled: _filled, className, controlRef, onMouseEnter, onMouseLeave, ...props },
    ref,
  ) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
      enter: ["fadeOut", "fadeIn"],
      leave: ["fadeIn"],
    });

    return (
      <svg
        ref={ref}
        aria-hidden="true"
        {...props}
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        viewBox="0 0 24 24"
        strokeWidth="2"
        className={cn(ICON_SIZE_CLASS[size], className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        {WIFI_LEVELS.map((level, index) => (
          <motion.path
            animate={controls}
            d={level.d}
            initial={{ opacity: level.initialOpacity }}
            key={index}
            variants={{
              fadeOut: {
                opacity: index === 0 ? 1 : 0,
                transition: { duration: 0.2 },
              },
              fadeIn: {
                opacity: 1,
                transition: {
                  type: "spring",
                  stiffness: 300,
                  damping: 20,
                  delay: level.delay,
                },
              },
            }}
          />
        ))}
      </svg>
    );
  },
);

WifiIcon.displayName = "WifiIcon";
