"use client";

// Generated by scripts/import-animated-icons.mjs — do not edit by hand.
// Source: lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com (registry item "wrench").
import type { Variants } from "motion/react";
import { motion } from "motion/react";
import * as React from "react";
import { cn } from "@/utils/cn";
import type { AnimatedIconHandle, AnimatedLegacyIconProps } from "./types";
import { useIconAnimation } from "./useIconAnimation";

const ICON_VARIANTS: Variants = {
  normal: {
    rotate: 0,
    transition: { duration: 0.25, ease: "easeOut" },
  },
  animate: {
    rotate: [0, 12, -14, 4, 0],
    transition: {
      duration: 1.05,
      times: [0, 0.42, 0.68, 0.88, 1],
      ease: ["easeInOut", "easeInOut", "easeOut", "easeOut"],
    },
  },
};

/** Props for {@link WrenchIcon}. See {@link AnimatedLegacyIconProps} for the shared shape. */
export type WrenchIconProps = AnimatedLegacyIconProps;

/** Imperative handle for {@link WrenchIcon}, via its `controlRef` prop. */
export type WrenchIconHandle = AnimatedIconHandle;

/**
 * Animated Wrench icon — the animated twin of `WrenchIcon` from
 * `@fanvue/ui`. Plays on hover, or on demand through `controlRef`.
 * Sized via `className`, defaulting to the same `size-6` box as the static icon.
 *
 * @example
 * ```tsx
 * import { WrenchIcon } from "@fanvue/ui/animated-icons";
 *
 * <WrenchIcon />
 * ```
 */
export const WrenchIcon = React.forwardRef<SVGSVGElement, WrenchIconProps>(
  ({ className, controlRef, onMouseEnter, onMouseLeave, ...props }, ref) => {
    const { controls, handleMouseEnter, handleMouseLeave } = useIconAnimation({
      controlRef,
      onMouseEnter,
      onMouseLeave,
    });

    return (
      <motion.svg
        ref={ref}
        animate={controls}
        fill="none"
        initial="normal"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        style={{ transformOrigin: "90% 10%", transformBox: "fill-box" }}
        variants={ICON_VARIANTS}
        viewBox="0 0 24 24"
        aria-hidden="true"
        className={cn("size-6", className)}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        {...props}
      >
        <path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z" />
      </motion.svg>
    );
  },
);

WrenchIcon.displayName = "WrenchIcon";
