/**
 * MDX emission helpers: name casing, escaping, and the JSX-attribute rules that
 * keep JSDoc prose (which is full of braces, angle brackets and backticks) from
 * breaking a Mintlify page.
 */

/** Header comment stamped on every generated file, so nobody hand-edits one. */
export const GENERATED_BANNER =
  "{/* GENERATED by fanv-ui scripts/generate-docs.mjs — do not edit. Source: fanvue/fanv-ui */}";

/**
 * `AiDisclosureBadge` -> `ai-disclosure-badge`, `DatePicker` -> `date-picker`.
 *
 * @param {string} name
 * @returns {string}
 */
export function kebabCase(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/**
 * `ai-disclosure-badge` -> `AiDisclosureBadge`. Used for the snippet component
 * names in a wrapper page, which must be valid JSX element names.
 *
 * @param {string} name
 * @returns {string}
 */
export function pascalCase(name) {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Escapes prose for MDX *outside* of inline code spans. Inside a code span MDX
 * suspends JSX parsing, so `` `Record<string, X>` `` is already safe and
 * escaping it would render the entity text literally — hence the split.
 *
 * @param {string} text
 * @returns {string}
 */
export function escapeMdxText(text) {
  if (!text) return "";
  const segments = text.split(/(`+[^`]*`+)/g);
  return segments
    .map((segment, index) =>
      index % 2 === 1
        ? segment
        : segment
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;")
            .replace(/\{/g, "&#123;")
            .replace(/\}/g, "&#125;"),
    )
    .join("");
}

/**
 * Turns a JSDoc description into a single MDX-safe line: `{@link Foo}` becomes
 * inline code, hard wraps collapse, and everything outside code spans is
 * escaped.
 *
 * @param {string | undefined} text
 * @returns {string}
 */
export function jsdocToMdx(text) {
  if (!text) return "";
  const withLinks = text
    .replace(/\{@link\s+([^}|]+)(?:\|[^}]*)?\}/g, (_match, target) => `\`${target.trim()}\``)
    .replace(
      /\{@(?:code|linkcode|linkplain)\s+([^}]+)\}/g,
      (_match, target) => `\`${target.trim()}\``,
    );
  const collapsed = withLinks
    .replace(/\s*\n\s*/g, " ")
    .replace(/\s{2,}/g, " ")
    .trim();
  return escapeMdxText(collapsed);
}

/**
 * Renders a JSX attribute. Single quotes are the default because prop types are
 * full of `"` — and when a value contains a single quote, or an `&` that MDX
 * would try to read as a character reference, the expression form sidesteps
 * both problems.
 *
 * @param {string} name
 * @param {string} value
 * @returns {string}
 */
export function jsxAttribute(name, value) {
  if (!/['&]/.test(value)) return `${name}='${value}'`;
  return `${name}={${JSON.stringify(value)}}`;
}

/**
 * Escapes the body of a fenced code block by picking a fence long enough to
 * contain it, so example source that itself contains ``` still renders.
 *
 * @param {string} code
 * @param {string} [language]
 * @returns {string}
 */
export function codeFence(code, language = "tsx") {
  const longest = (code.match(/`{3,}/g) ?? []).reduce((max, run) => Math.max(max, run.length), 2);
  const fence = "`".repeat(Math.max(3, longest + 1));
  return `${fence}${language}\n${code.trimEnd()}\n${fence}`;
}
