/**
 * Optional animated icon entry point — `@fanvue/ui/animated-icons`.
 *
 * Every export here mirrors an icon of the same name in `@fanvue/ui` and renders
 * in the same box, so an animated icon is a drop-in for its static twin:
 *
 * ```tsx
 * import { HeartIcon } from "@fanvue/ui";                 // static
 * import { HeartIcon } from "@fanvue/ui/animated-icons";  // animates on hover
 * ```
 *
 * Requires the optional `motion` peer dependency (`pnpm add motion`). Kept on its
 * own subpath so `@fanvue/ui` consumers never pay for Motion unless they opt in.
 *
 * Artwork and animations from lucide-animated (MIT, (c) 2024-2026 pqoqubbw) — https://lucide-animated.com.
 * Generated by scripts/import-animated-icons.mjs — do not edit by hand.
 */
export type { AddIconHandle, AddIconProps } from "./components/AnimatedIcons/AddIcon";
export { AddIcon } from "./components/AnimatedIcons/AddIcon";
export type {
  AffiliatesIconHandle,
  AffiliatesIconProps,
} from "./components/AnimatedIcons/AffiliatesIcon";
export { AffiliatesIcon } from "./components/AnimatedIcons/AffiliatesIcon";
export type { AIIconHandle, AIIconProps } from "./components/AnimatedIcons/AIIcon";
export { AIIcon } from "./components/AnimatedIcons/AIIcon";
export type {
  ArrowDownIconHandle,
  ArrowDownIconProps,
} from "./components/AnimatedIcons/ArrowDownIcon";
export { ArrowDownIcon } from "./components/AnimatedIcons/ArrowDownIcon";
export type {
  ArrowLeftIconHandle,
  ArrowLeftIconProps,
} from "./components/AnimatedIcons/ArrowLeftIcon";
export { ArrowLeftIcon } from "./components/AnimatedIcons/ArrowLeftIcon";
export type {
  ArrowRightIconHandle,
  ArrowRightIconProps,
} from "./components/AnimatedIcons/ArrowRightIcon";
export { ArrowRightIcon } from "./components/AnimatedIcons/ArrowRightIcon";
export type { ArrowUpIconHandle, ArrowUpIconProps } from "./components/AnimatedIcons/ArrowUpIcon";
export { ArrowUpIcon } from "./components/AnimatedIcons/ArrowUpIcon";
export type {
  ArrowUpRightIconHandle,
  ArrowUpRightIconProps,
} from "./components/AnimatedIcons/ArrowUpRightIcon";
export { ArrowUpRightIcon } from "./components/AnimatedIcons/ArrowUpRightIcon";
export type { AtSignIconHandle, AtSignIconProps } from "./components/AnimatedIcons/AtSignIcon";
export { AtSignIcon } from "./components/AnimatedIcons/AtSignIcon";
export type { BellIconHandle, BellIconProps } from "./components/AnimatedIcons/BellIcon";
export { BellIcon } from "./components/AnimatedIcons/BellIcon";
export type { BoltIconHandle, BoltIconProps } from "./components/AnimatedIcons/BoltIcon";
export { BoltIcon } from "./components/AnimatedIcons/BoltIcon";
export type {
  CalendarIconHandle,
  CalendarIconProps,
} from "./components/AnimatedIcons/CalendarIcon";
export { CalendarIcon } from "./components/AnimatedIcons/CalendarIcon";
export type { CardIconHandle, CardIconProps } from "./components/AnimatedIcons/CardIcon";
export { CardIcon } from "./components/AnimatedIcons/CardIcon";
export type { CheckIconHandle, CheckIconProps } from "./components/AnimatedIcons/CheckIcon";
export { CheckIcon } from "./components/AnimatedIcons/CheckIcon";
export type {
  CheckOutlineIconHandle,
  CheckOutlineIconProps,
} from "./components/AnimatedIcons/CheckOutlineIcon";
export { CheckOutlineIcon } from "./components/AnimatedIcons/CheckOutlineIcon";
export type {
  ChevronDownIconHandle,
  ChevronDownIconProps,
} from "./components/AnimatedIcons/ChevronDownIcon";
export { ChevronDownIcon } from "./components/AnimatedIcons/ChevronDownIcon";
export type {
  ChevronLeftIconHandle,
  ChevronLeftIconProps,
} from "./components/AnimatedIcons/ChevronLeftIcon";
export { ChevronLeftIcon } from "./components/AnimatedIcons/ChevronLeftIcon";
export type {
  ChevronRightIconHandle,
  ChevronRightIconProps,
} from "./components/AnimatedIcons/ChevronRightIcon";
export { ChevronRightIcon } from "./components/AnimatedIcons/ChevronRightIcon";
export type {
  ChevronUpIconHandle,
  ChevronUpIconProps,
} from "./components/AnimatedIcons/ChevronUpIcon";
export { ChevronUpIcon } from "./components/AnimatedIcons/ChevronUpIcon";
export type { ClockIconHandle, ClockIconProps } from "./components/AnimatedIcons/ClockIcon";
export { ClockIcon } from "./components/AnimatedIcons/ClockIcon";
export type { CloseIconHandle, CloseIconProps } from "./components/AnimatedIcons/CloseIcon";
export { CloseIcon } from "./components/AnimatedIcons/CloseIcon";
export type { CogIconHandle, CogIconProps } from "./components/AnimatedIcons/CogIcon";
export { CogIcon } from "./components/AnimatedIcons/CogIcon";
export type { CoinIconHandle, CoinIconProps } from "./components/AnimatedIcons/CoinIcon";
export { CoinIcon } from "./components/AnimatedIcons/CoinIcon";
export type { CopyIconHandle, CopyIconProps } from "./components/AnimatedIcons/CopyIcon";
export { CopyIcon } from "./components/AnimatedIcons/CopyIcon";
export type { CrossIconHandle, CrossIconProps } from "./components/AnimatedIcons/CrossIcon";
export { CrossIcon } from "./components/AnimatedIcons/CrossIcon";
export type { DiscordIconHandle, DiscordIconProps } from "./components/AnimatedIcons/DiscordIcon";
export { DiscordIcon } from "./components/AnimatedIcons/DiscordIcon";
export type {
  DoubleTickIconHandle,
  DoubleTickIconProps,
} from "./components/AnimatedIcons/DoubleTickIcon";
export { DoubleTickIcon } from "./components/AnimatedIcons/DoubleTickIcon";
export type {
  DownloadIconHandle,
  DownloadIconProps,
} from "./components/AnimatedIcons/DownloadIcon";
export { DownloadIcon } from "./components/AnimatedIcons/DownloadIcon";
export type { EmojiIconHandle, EmojiIconProps } from "./components/AnimatedIcons/EmojiIcon";
export { EmojiIcon } from "./components/AnimatedIcons/EmojiIcon";
export type { ExpandIconHandle, ExpandIconProps } from "./components/AnimatedIcons/ExpandIcon";
export { ExpandIcon } from "./components/AnimatedIcons/ExpandIcon";
export type { EyeIconHandle, EyeIconProps } from "./components/AnimatedIcons/EyeIcon";
export { EyeIcon } from "./components/AnimatedIcons/EyeIcon";
export type { EyeOffIconHandle, EyeOffIconProps } from "./components/AnimatedIcons/EyeOffIcon";
export { EyeOffIcon } from "./components/AnimatedIcons/EyeOffIcon";
export type { FlameIconHandle, FlameIconProps } from "./components/AnimatedIcons/FlameIcon";
export { FlameIcon } from "./components/AnimatedIcons/FlameIcon";
export type { HeartIconHandle, HeartIconProps } from "./components/AnimatedIcons/HeartIcon";
export { HeartIcon } from "./components/AnimatedIcons/HeartIcon";
export type { HelpIconHandle, HelpIconProps } from "./components/AnimatedIcons/HelpIcon";
export { HelpIcon } from "./components/AnimatedIcons/HelpIcon";
export type { HomeIconHandle, HomeIconProps } from "./components/AnimatedIcons/HomeIcon";
export { HomeIcon } from "./components/AnimatedIcons/HomeIcon";
export type {
  HourglassIconHandle,
  HourglassIconProps,
} from "./components/AnimatedIcons/HourglassIcon";
export { HourglassIcon } from "./components/AnimatedIcons/HourglassIcon";
export type {
  LanguageIconHandle,
  LanguageIconProps,
} from "./components/AnimatedIcons/LanguageIcon";
export { LanguageIcon } from "./components/AnimatedIcons/LanguageIcon";
export type { LinkIconHandle, LinkIconProps } from "./components/AnimatedIcons/LinkIcon";
export { LinkIcon } from "./components/AnimatedIcons/LinkIcon";
export type {
  LocationIconHandle,
  LocationIconProps,
} from "./components/AnimatedIcons/LocationIcon";
export { LocationIcon } from "./components/AnimatedIcons/LocationIcon";
export type { LockerIconHandle, LockerIconProps } from "./components/AnimatedIcons/LockerIcon";
export { LockerIcon } from "./components/AnimatedIcons/LockerIcon";
export type {
  LockerOnIconHandle,
  LockerOnIconProps,
} from "./components/AnimatedIcons/LockerOnIcon";
export { LockerOnIcon } from "./components/AnimatedIcons/LockerOnIcon";
export type {
  MenuCloseIconHandle,
  MenuCloseIconProps,
} from "./components/AnimatedIcons/MenuCloseIcon";
export { MenuCloseIcon } from "./components/AnimatedIcons/MenuCloseIcon";
export type { MenuIconHandle, MenuIconProps } from "./components/AnimatedIcons/MenuIcon";
export { MenuIcon } from "./components/AnimatedIcons/MenuIcon";
export type {
  MenuOpenIconHandle,
  MenuOpenIconProps,
} from "./components/AnimatedIcons/MenuOpenIcon";
export { MenuOpenIcon } from "./components/AnimatedIcons/MenuOpenIcon";
export type {
  MicrophoneIconHandle,
  MicrophoneIconProps,
} from "./components/AnimatedIcons/MicrophoneIcon";
export { MicrophoneIcon } from "./components/AnimatedIcons/MicrophoneIcon";
export type {
  NewMessageIconHandle,
  NewMessageIconProps,
} from "./components/AnimatedIcons/NewMessageIcon";
export { NewMessageIcon } from "./components/AnimatedIcons/NewMessageIcon";
export type { OpenIconHandle, OpenIconProps } from "./components/AnimatedIcons/OpenIcon";
export { OpenIcon } from "./components/AnimatedIcons/OpenIcon";
export type { PeopleIconHandle, PeopleIconProps } from "./components/AnimatedIcons/PeopleIcon";
export { PeopleIcon } from "./components/AnimatedIcons/PeopleIcon";
export type { PhoneIconHandle, PhoneIconProps } from "./components/AnimatedIcons/PhoneIcon";
export { PhoneIcon } from "./components/AnimatedIcons/PhoneIcon";
export type { PlusIconHandle, PlusIconProps } from "./components/AnimatedIcons/PlusIcon";
export { PlusIcon } from "./components/AnimatedIcons/PlusIcon";
export type { ReverseIconHandle, ReverseIconProps } from "./components/AnimatedIcons/ReverseIcon";
export { ReverseIcon } from "./components/AnimatedIcons/ReverseIcon";
export type { SearchIconHandle, SearchIconProps } from "./components/AnimatedIcons/SearchIcon";
export { SearchIcon } from "./components/AnimatedIcons/SearchIcon";
export type { SendIconHandle, SendIconProps } from "./components/AnimatedIcons/SendIcon";
export { SendIcon } from "./components/AnimatedIcons/SendIcon";
export type {
  SettingsIconHandle,
  SettingsIconProps,
} from "./components/AnimatedIcons/SettingsIcon";
export { SettingsIcon } from "./components/AnimatedIcons/SettingsIcon";
export type { SoundIconHandle, SoundIconProps } from "./components/AnimatedIcons/SoundIcon";
export { SoundIcon } from "./components/AnimatedIcons/SoundIcon";
export type { SpinnerIconHandle, SpinnerIconProps } from "./components/AnimatedIcons/SpinnerIcon";
export { SpinnerIcon } from "./components/AnimatedIcons/SpinnerIcon";
export type { SunIconHandle, SunIconProps } from "./components/AnimatedIcons/SunIcon";
export { SunIcon } from "./components/AnimatedIcons/SunIcon";
export type {
  ThumbDownIconHandle,
  ThumbDownIconProps,
} from "./components/AnimatedIcons/ThumbDownIcon";
export { ThumbDownIcon } from "./components/AnimatedIcons/ThumbDownIcon";
export type { ThumbUpIconHandle, ThumbUpIconProps } from "./components/AnimatedIcons/ThumbUpIcon";
export { ThumbUpIcon } from "./components/AnimatedIcons/ThumbUpIcon";
export type {
  TickCircleIconHandle,
  TickCircleIconProps,
} from "./components/AnimatedIcons/TickCircleIcon";
export { TickCircleIcon } from "./components/AnimatedIcons/TickCircleIcon";
export type { TickIconHandle, TickIconProps } from "./components/AnimatedIcons/TickIcon";
export { TickIcon } from "./components/AnimatedIcons/TickIcon";
export type {
  TrashBinIconHandle,
  TrashBinIconProps,
} from "./components/AnimatedIcons/TrashBinIcon";
export { TrashBinIcon } from "./components/AnimatedIcons/TrashBinIcon";
export type { TrashIconHandle, TrashIconProps } from "./components/AnimatedIcons/TrashIcon";
export { TrashIcon } from "./components/AnimatedIcons/TrashIcon";
export type {
  AnimatedIconHandle,
  AnimatedIconProps,
  AnimatedLegacyIconProps,
} from "./components/AnimatedIcons/types";
export type {
  UploadCloudIconHandle,
  UploadCloudIconProps,
} from "./components/AnimatedIcons/UploadCloudIcon";
export { UploadCloudIcon } from "./components/AnimatedIcons/UploadCloudIcon";
export type { UploadIconHandle, UploadIconProps } from "./components/AnimatedIcons/UploadIcon";
export { UploadIcon } from "./components/AnimatedIcons/UploadIcon";
export type {
  UploadToCloudIconHandle,
  UploadToCloudIconProps,
} from "./components/AnimatedIcons/UploadToCloudIcon";
export { UploadToCloudIcon } from "./components/AnimatedIcons/UploadToCloudIcon";
export type { UsersIconHandle, UsersIconProps } from "./components/AnimatedIcons/UsersIcon";
export { UsersIcon } from "./components/AnimatedIcons/UsersIcon";
export type { WalletIconHandle, WalletIconProps } from "./components/AnimatedIcons/WalletIcon";
export { WalletIcon } from "./components/AnimatedIcons/WalletIcon";
export type { WifiIconHandle, WifiIconProps } from "./components/AnimatedIcons/WifiIcon";
export { WifiIcon } from "./components/AnimatedIcons/WifiIcon";
export type { WifiOnIconHandle, WifiOnIconProps } from "./components/AnimatedIcons/WifiOnIcon";
export { WifiOnIcon } from "./components/AnimatedIcons/WifiOnIcon";
export type { WrenchIconHandle, WrenchIconProps } from "./components/AnimatedIcons/WrenchIcon";
export { WrenchIcon } from "./components/AnimatedIcons/WrenchIcon";
